import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/Components/Navbar";
import Hero from "@/Components/Hero";
import Team from "@/Components/Team";
import Footer from "@/Components/Footer";
import ChallengeCard0 from "@/Components/Challenges/Challenge #0";
import ChallengeCard1 from "@/Components/Challenges/Challenge #1";
import ChallengeCard2 from "@/Components/Challenges/Challenge #2";
import ChallengeCard3 from "@/Components/Challenges/Challenge #3";
import ChallengeCard4 from "@/Components/Challenges/Challenge #4";
import ChallengeCard5 from "@/Components/Challenges/Challenge #5";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SpeedRun Ethereum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main
        id="home"
        className="bg-base-100 lg:h-screen flex justify-center items-center w-full max-md:min-h-screen overflow-x-hidden"
      >
        <Hero />
      </main>
      <section
        id="solutions"
        className="bg-base-100 min-h-screen flex flex-col justify-center items-center w-full overflow-x-hidden"
      >
        <ChallengeCard0 />
        <ChallengeCard1 />
        <ChallengeCard2 />
        <ChallengeCard3 />
        <ChallengeCard4 />
        <ChallengeCard5 />
      </section>
      <section
        id="team"
        className="bg-base-100 lg:min-h-[50vh] flex justify-center items-start w-full lg:my-28 overflow-x-hidden"
      >
        <Team />
      </section>
      <section id="team" className="flex justify-center items-start w-full">
        <Footer />
      </section>
    </>
  );
}
